FINANCIAL = 'financial'
MANAGEMENT_CONSULTING = 'management-consulting'
HUMAN_RESOURCES = 'human-resources'
LEGAL = 'legal'
PUBLICITY = 'publicity'
BUSINESS_SUPPORT = 'business-support'
OTHER = 'other'
